var quotes = [
    "“When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out.” — Eleanor Roosevelt",
    "“Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too.” — Mark Twain",
    "“Learn as if you will live forever, live like you will die tomorrow.” — Mahatma Gandhi",
    "“We cannot solve problems with the kind of thinking we employed when we came up with them.” — Albert Einstein",
    "“When you change your thoughts, remember to also change your world.” —Norman Vincent Peale",
    "“It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest.“ —Walter Anderson",
    "“Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together.” —Diane McLaren",
    "“Success is not final; failure is not fatal: It is the courage to continue that counts.“ — Winston S. Churchill",
    "“It is better to fail in originality than to succeed in imitation.” — Herman Melville",
    "“The road to success and the road to failure are almost exactly the same.” — Colin R. Davis",
    "“Success usually comes to those who are too busy looking for it.” — Henry David Thoreau",
    "“Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.” —Dale Carnegie",
    "“There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind.” —Mister Rogers",
    "“I never dreamed about success. I worked for it.” —Estée Lauder",
    "“Success is getting what you want, happiness is wanting what you get.” ―W. P. Kinsella",
    "“The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.” — Winston Churchill",
    "“Don’t let yesterday take up too much of today.” — Will Rogers",
    "“You learn more from failure than from success. Don’t let it stop you. Failure builds character.” — Unknown ",
    "“If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.” — Steve Jobs",
    "“Experience is a hard teacher because she gives the test first, the lesson afterwards.” ―Vernon Sanders Law",
    "“To know how much there is to know is the beginning of learning to live.” —Dorothy West",
    "“Either you run the day or the day runs you.” — Jim Rohn",
    "“I’m a greater believer in luck, and I find the harder I work the more I have of it.” — Thomas Jefferson",
    "“When we strive to become better than we are, everything around us becomes better too.” — Paulo Coelho",
    "“Opportunity is missed by most people because it is dressed in overalls and looks like work.” — Thomas Edison",
    "“Setting goals is the first step in turning the invisible into the visible.” — Tony Robbins",
    "Women challenge the status quo because we are never it.” — Cindy Gallop",
    "We don’t just sit around and wait for other people. We just make, and we do.” — Arlan Hamilton",
    "“Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.” — Oprah Winfrey",
    "“The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could.” — Unknown",
    "“Whenever you see a successful woman, look out for three men who are going out of their way to try to block her.” – Yulia Tymoshenko",
    "“The thing women have yet to learn is nobody gives you power. You just take it. ” ― Roseanne Barr",
    "“No woman wants to be in submission to a man who isn’t in submission to God!” ― T D Jakes",
    "“A witty woman is a treasure; a witty beauty is a power.” ― George Meredith",
    "“When a woman becomes her own best friend life is easier.” – Diane Von Furstenberg",
    "“If you want something said, ask a man; if you want something done, ask a woman.” – Margaret Thatcher",
    "“It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent.” – Madeleine Albright",
    "“Women must learn to play the game as men do.” – Eleanor Roosevelt",
    "“I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine.” — Ayn Rand",
    "“He who conquers himself is the mightiest warrior.” — Confucius ",
    "“Try not to become a man of success, but rather become a man of value.” – Albert Einstein",
    "“One man with courage makes a majority.” – Andrew Jackson",
    "“One secret of success in life is for a man to be ready for his opportunity when it comes.” – Benjamin Disraeli",
    "“A man who has committed a mistake and doesn’t correct it is committing another mistake.” – Confucius Kongzi",
    "“The successful man will profit from his mistakes and try again in a different way.” – Dale Carnegie",
    "“A successful man is one who can lay a firm foundation with the bricks others have thrown at him.” – David Brinkley",
    "“He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.” – Epictetus",
    "“You've got to get up every morning with determination if you're going to go to bed with satisfaction.” — George Lorimer",
    "“Education is the most powerful weapon which you can use to change the world.” — Nelson Mandela",
    "“The most difficult thing is the decision to act, the rest is merely tenacity.” —Amelia Earhart",

]

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
